name: Build and Release Game Executable

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install pyinstaller

      - name: Build Executable
        run: |
          if [ "$RUNNER_OS" = "macOS" ]; then
            pyinstaller --onefile --windowed --name "LastThingsLast" main.py
          else
            pyinstaller --onefile --name "LastThingsLast" main.py
          fi
        shell: bash

      - name: Create .dmg Installer (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          # Install create-dmg if not already installed
          brew install create-dmg

          # Check if any .dmg file already exists, and delete it
          echo "Removing any existing .dmg files to avoid confusion:"
          rm -f dist/LastThingsLast-${{ github.ref_name }}.dmg

          #    Check the contents of the dist folder to verify the .app exists
          echo "Listing contents of dist directory:"
          ls -R dist

          # Check file permissions for the .app (make sure it's accessible)
          echo "Checking file permissions for the .app:"
          ls -l dist/LastThingsLast.app

          # Now run create-dmg and specify the output filename
          echo "Creating .dmg file with create-dmg:"
          create-dmg 'dist/LastThingsLast.app' 'dist/LastThingsLast-${{ github.ref_name }}.dmg' \
            --dmg-title="LastThingsLast Installer" \
            --overwrite || echo "create-dmg failed"

        shell: bash

      - name: Rename Executables
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            mv dist/LastThingsLast.exe dist/game-windows-${{ github.ref_name }}.exe
          elif [ "$RUNNER_OS" = "macOS" ]; then
            mv dist/LastThingsLast.dmg dist/game-macos-${{ github.ref_name }}.dmg
          fi
        shell: bash

      - name: Upload Executable to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            dist/game-windows-${{ github.ref_name }}.exe
            dist/game-macos-${{ github.ref_name }}.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
